Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new AbstractClasses().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new Composition().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new Generics().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new HeadToHead().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new InheritanceVehicleExample().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new Interfaces().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new ProtectedAndVirtual().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
new Tuples().RunExample();
Console.WriteLine();
Console.WriteLine("____________________________________");
Console.WriteLine();
